name: Unit Tests
description: 'Execute app unit tests'
runs:
  using: "composite"
  steps:
    - name: SetUp Java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8

    - name: Decode google-services.json
      env:
        FIREBASE_SECRET_DEV: ${{ secrets.FIREBASE_SECRET_DEV }}
      run: echo $FIREBASE_SECRET_DEV > app/google-services.json
    - name: Run unit tests
      run: ./gradlew clean test