name: Continuous Integration

on:
  push:
    branches: [ master, development, test_ui_labtest_firebase ]
#   pull_request:
#     branches: [ master, development ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: SetUp Java
        uses: actions/setup-java@v1.4.3
        with: 
          java-version: 1.8
      
      - name: Decode google-services.json
        env:
          FIREBASE_SECRET_DEV: ${{ secrets.FIREBASE_SECRET_DEV }}
        run: echo $FIREBASE_SECRET_DEV > app/google-services.json
      - name: Run unit tests
        run: ./gradlew clean test
#       - name: Run instrumentation tests
#         uses: reactivecircus/android-emulator-runner@v2
#         with:
#           api-level: 29
#           arch: x86_64
#           script: ./gradlew connectedCheck
      # Run the Firebase Test Lab Action
      - name: Run tests on Firebase Test Lab
        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
        with:
          arg-spec: 'tests.yml:android-pixel-4'
        env:
          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SECRET_DEV }}
          # SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Generate APK
        run: ./gradlew clean assembleDebug
      - name: Rename APK
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/botaprarodar.apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: APK generated
          path: app/build/outputs/apk/debug/botaprarodar.apk
