name: Continuous Integration

on:
  push:
    branches: [ main, development, test_ui_labtest_firebase ]
  pull_request:
    branches: [ main, development ]
jobs:
  build:
    name: Unit Tests
    runs-on: macos-latest
    steps:
      - uses: ./.github/actions/unit_tests
